# Training configuration
dataset_path: "salesforce/wikitext"
dataset_name: "wikitext-2-raw-v1"
train_epochs: 10
eval_freq: 1
model_save_folder_path: None
metrics_save_folder_path: None
learning_rate: 5e-4
weight_decay: 5e-3
max_seq_len: 128
batch_size: 4
use_fsdp: false
seed: 6969

# Model configuration
# Notes on model configuration:
# For Mamba2 head_dims, hidden_dim/concept_dim * mamba_expand / head_dim must be a multiple of 8

# Model configuration settings
hidden_dim: 512
concept_dim: 768
vocab_size: 129280
dist_desired_std: 1.0
num_encoder_layers: 2
num_decoder_layers: 2
mamba_state_dim: 8
mamba_conv_length: 4
mamba_expand: 2
mamba_head_dim: 64 # (hidden_dim * mamba_expand / mamba_head_dim = 64 = 8 * 8)
mlp_inner_dim: 768
confidence_inner_dim: 768
segment_pred_inner_dim: 768

# Q-Net configuration
enable_qnet: true # We advise Q-Net to be enabled to reduce the chance of posterior collapse
num_qnet_layers: 1
qnet_conv_length: 4
qnet_mamba_expand: 1
qnet_mamba_head_dim: 48 # (concept_dim * mamba_expand / qnet_mamba_head_dim = 48 = 8 * 6)
qnet_mlp_inner_dim: 384
qnet_mamba_state_dim: 8

# Embedding configuration
share_input_embeddings: true
tie_embeddings: true

# Hardware configuration
residual_in_fp32: false
device: "cuda"
dtype: "bf16"